FROM python:3.11-slim

WORKDIR /app

COPY Ingestion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Ingestion/MySQL_Connector.py .

ENTRYPOINT ["python", "MySQL_Connector.py"]