# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests + lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest ruff
          pip install -r Ingestion/requirements.txt

      - name: Lint with ruff
        run: ruff check Ingestion/

      - name: Run unit tests
        run: pytest Test/ -v

  docker-build-smoke-test-and-push:
    name: Docker build smoke test and push
    runs-on: ubuntu-latest
    needs: unit-tests

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build ingestion image
        run: docker build -f Docker/Dockerfile.ingestion -t $ECR_REGISTRY/olist-ingestion:${{ github.sha }} .

      - name: Build dbt image
        run: docker build -f Docker/Dockerfile.dbt -t $ECR_REGISTRY/olist-dbt:${{ github.sha }} .

      - name: Smoke test ingestion image
        run: docker run --rm --entrypoint python $ECR_REGISTRY/olist-ingestion:${{ github.sha }} --version

      - name: Smoke test dbt image
        run: docker run --rm $ECR_REGISTRY/olist-dbt:${{ github.sha }} --version

      - name: Push ingestion image
        run: docker push $ECR_REGISTRY/olist-ingestion:${{ github.sha }}

      - name: Push dbt image
        run: docker push $ECR_REGISTRY/olist-dbt:${{ github.sha }}