# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests + lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest ruff
          pip install -r Ingestion/requirements.txt

      - name: Lint with ruff
        run: ruff check Ingestion/

      - name: Run unit tests
        run: pytest Test/ -v
  docker-build-and-smoke-test:
    name: Build + smoke test Docker images
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ingestion image
        run: docker build -f Docker/Dockerfile.ingestion -t olist-ingestion .

      - name: Build dbt image
        run: docker build -f Docker/Dockerfile.dbt -t olist-dbt .

      - name: Smoke test ingestion image
        run: docker run --rm --entrypoint python olist-ingestion --version

      - name: Smoke test dbt image
        run: docker run --rm olist-dbt --version